version: '3.8'

services:
  postgres:
    image: postgres:14.9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@asdf.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
  ng-server:
    build: .
    ports:
      - "9000:9000"
volumes:
  data:
